language: csharp

env:
  global:
    - EnableNuGetPackageRestore=true

solution: GreyListAgent.sln

cache: apt

script:
  - xbuild GreyListAgent.sln /p:Configuration=2013
  - xbuild GreyListAgent.sln /p:Configuration=2013CU1
  - xbuild GreyListAgent.sln /p:Configuration=2013CU2
  - xbuild GreyListAgent.sln /p:Configuration=2013CU3
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU4
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU5
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU6
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU7
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU8
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU9
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU10
  - xbuild GreyListAgent.sln /p:Configuration=2013SP1CU11
  - xbuild GreyListAgent.sln /p:Configuration=2016RTM
  - xbuild GreyListAgent.sln /p:Configuration=Release
