language: csharp

env:
  global:
    - EnableNuGetPackageRestore=true
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "kC7O0CWm9h4g+tzCwhIZEGwcdiLrb1/1PijeOKGbIWGuWS7cIksAkj2tRNMgtxxcE9CFQr8W7xDv2YzflCIlqN1nGkFjbyD4CrNg6+V1j0fZjPOQ6ssdBBVPrfrvecsAUJ0/48Tqa9VTkEpZSlwOF/VS1sO2ob36FVyWjtxvG9s="

  matrix:
    - MONO_VERSION="3.10.0"

git:
  submodules: false

solution: src/GreyListAgent.sln

cache: apt

script:
  - xbuild src/GreyListAgent.sln /p:Configuration=2013
  - xbuild src/GreyListAgent.sln /p:Configuration=2013CU1
  - xbuild src/GreyListAgent.sln /p:Configuration=2013CU2
  - xbuild src/GreyListAgent.sln /p:Configuration=2013CU3
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU4
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU5
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU6
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU7
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU8
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU9
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU10
  - xbuild src/GreyListAgent.sln /p:Configuration=2013SP1CU11
  - xbuild src/GreyListAgent.sln /p:Configuration=2016RTM
  - xbuild src/GreyListAgent.sln /p:Configuration=Release
